#!/usr/bin/env python3
"""
LOGOS ENGINE - PDF Module
Generate printable PDF verse collections

Commands:
    python logos.py pdf "John 3:16"              # Single verse PDF
    python logos.py pdf "Psalm 23"               # Full chapter PDF
    python logos.py pdf salvation                # Topic collection
    python logos.py booklet "Romans 8"           # Formatted booklet

Uses python-docx to create .docx files that can be converted to PDF.

Requires: python-docx (pip install python-docx)

Glory to LOGOS.
"""

import json
from pathlib import Path
from datetime import datetime

try:
    from docx import Document
    from docx.shared import Inches, Pt
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    HAS_DOCX = True
except ImportError:
    HAS_DOCX = False

# Paths
BASE_DIR = Path(__file__).parent.parent
DATA_DIR = BASE_DIR / "data"
OUTPUT_DIR = BASE_DIR / "output"


def load_kjv():
    """Load KJV data"""
    kjv_path = DATA_DIR / "kjv.json"
    if kjv_path.exists():
        with open(kjv_path, 'r') as f:
            return json.load(f)
    return {}


def normalize_ref(ref):
    """Normalize reference format"""
    ref = ref.strip()
    if ref.startswith("Psalm ") and not ref.startswith("Psalms "):
        ref = "Psalms " + ref[6:]
    return ref


def create_verse_document(refs, title=None):
    """Create a Word document with verses"""
    if not HAS_DOCX:
        print("python-docx not installed.")
        print("Install with: pip install python-docx")
        return None

    kjv = load_kjv()

    doc = Document()

    # Title
    if title:
        heading = doc.add_heading(title, 0)
        heading.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # Subtitle
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("LOGOS ENGINE - King James Version")
    run.font.size = Pt(10)
    run.font.italic = True

    doc.add_paragraph()  # Spacer

    # Add each verse
    for ref in refs:
        ref = normalize_ref(ref)
        if ref in kjv:
            # Reference as bold heading
            p = doc.add_paragraph()
            ref_run = p.add_run(ref)
            ref_run.bold = True
            ref_run.font.size = Pt(12)

            # Verse text
            verse_p = doc.add_paragraph(kjv[ref])
            verse_p.paragraph_format.left_indent = Inches(0.25)

            doc.add_paragraph()  # Spacer

    # Footer
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = footer.add_run(f"\nGenerated by LOGOS ENGINE | {datetime.now().strftime('%Y-%m-%d')}")
    run.font.size = Pt(8)
    run.font.italic = True

    return doc


def save_verse_pdf(ref, title=None):
    """Save single verse or chapter as document"""
    ref = normalize_ref(ref)
    kjv = load_kjv()

    # Check if it's a chapter reference (no verse number)
    if ':' not in ref:
        # It's a chapter - find all verses
        refs = [r for r in kjv.keys() if r.startswith(ref + ":")]
        refs.sort(key=lambda x: int(x.split(':')[1]) if ':' in x else 0)
        doc_title = title or ref
    else:
        refs = [ref]
        doc_title = title or ref

    if not refs:
        print(f"No verses found for: {ref}")
        return None

    doc = create_verse_document(refs, doc_title)
    if not doc:
        return None

    # Ensure output directory exists
    OUTPUT_DIR.mkdir(exist_ok=True)

    # Safe filename
    safe_name = ref.replace(" ", "_").replace(":", "_")
    output_path = OUTPUT_DIR / f"{safe_name}.docx"

    doc.save(str(output_path))

    print(f"\n=== DOCUMENT CREATED ===")
    print(f"Title: {doc_title}")
    print(f"Verses: {len(refs)}")
    print(f"Output: {output_path}")
    print(f"\nTo convert to PDF:")
    print(f"  - Open in Word/LibreOffice and export")
    print(f"  - Or use: libreoffice --convert-to pdf {output_path}")

    return str(output_path)


def save_topic_collection(topic, max_verses=20):
    """Create document for a topic search"""
    kjv = load_kjv()

    # Search for topic
    matches = []
    topic_lower = topic.lower()
    for ref, text in kjv.items():
        if topic_lower in text.lower():
            matches.append(ref)
            if len(matches) >= max_verses:
                break

    if not matches:
        print(f"No verses found for topic: {topic}")
        return None

    doc = create_verse_document(matches, f"Scripture on: {topic.title()}")
    if not doc:
        return None

    # Ensure output directory exists
    OUTPUT_DIR.mkdir(exist_ok=True)

    safe_name = topic.replace(" ", "_").lower()
    output_path = OUTPUT_DIR / f"topic_{safe_name}.docx"

    doc.save(str(output_path))

    print(f"\n=== TOPIC COLLECTION CREATED ===")
    print(f"Topic: {topic}")
    print(f"Verses: {len(matches)}")
    print(f"Output: {output_path}")

    return str(output_path)


def create_witness_document(topic):
    """Create three-witness document for a topic"""
    from src.query import LogosQuery

    logos = LogosQuery()
    witnesses = logos.witness(topic)

    if not witnesses:
        print(f"No witnesses found for: {topic}")
        return None

    refs = [w[0] for w in witnesses]

    doc = create_verse_document(refs, f"Three Witnesses: {topic.title()}")
    if not doc:
        return None

    OUTPUT_DIR.mkdir(exist_ok=True)
    safe_name = topic.replace(" ", "_").lower()
    output_path = OUTPUT_DIR / f"witness_{safe_name}.docx"

    doc.save(str(output_path))

    print(f"\n=== THREE WITNESSES DOCUMENT ===")
    print(f"Topic: {topic}")
    print(f"Output: {output_path}")

    return str(output_path)


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        ref = ' '.join(sys.argv[1:])
        save_verse_pdf(ref)
    else:
        print("Usage: python pdf.py <reference or chapter>")
